export type BilingualText = [string, string];
export type ReactionId = "carbon" | "neutron" | "fluorine" | "magnesium";
export type Paper = {
  slug: string;
  reactionId: ReactionId | "review";
  kind: "research" | "review";
  language: "en";
  authors: string;
  citation: string;
  bibtex: string;
  volume: string;
  pages: string;
  publishedOnline?: string;
  doi: string;
  url: string;
  journal: string;
  year: string;
  title: BilingualText;
  englishTitle: string;
  summary: BilingualText;
  detail: BilingualText;
};
export const papers: Paper[] = [
  {slug:"cno-breakout-2022",reactionId:"fluorine",authors:"Liyong Zhang et al.",volume:"610",pages:"656–660",publishedOnline:"2022-10-26",kind:"research",language:"en",citation:"Liyong Zhang et al. Measurement of ¹⁹F(p, γ)²⁰Ne reaction suggests CNO breakout in first stars. Nature 610, 656–660 (2022). https://doi.org/10.1038/s41586-022-05230-x",bibtex:"@article{Zhang2022CNOBreakout,\n  author = {Zhang, Liyong and others},\n  title = {Measurement of {$^{19}$F(p, $\\gamma$)$^{20}$Ne} reaction suggests {CNO} breakout in first stars},\n  journal = {Nature},\n  year = {2022},\n  volume = {610},\n  pages = {656--660},\n  doi = {10.1038/s41586-022-05230-x},\n  url = {https://doi.org/10.1038/s41586-022-05230-x},\n}",doi:"10.1038/s41586-022-05230-x",url:"https://doi.org/10.1038/s41586-022-05230-x",journal:"Nature",year:"2022",title:["第一代恒星中的 CNO 循环突破反应","CNO breakout in the first stars"],englishTitle:"Measurement of ¹⁹F(p, γ)²⁰Ne reaction suggests CNO breakout in first stars",summary:["测量 ¹⁹F(p,γ)²⁰Ne 反应，为第一代恒星中钙的形成途径提供实验依据。","A measurement of ¹⁹F(p,γ)²⁰Ne constrains a pathway for calcium production in the first stars."],detail:["JUNA 对 ¹⁹F(p,γ)²⁰Ne 的低能测量，为物质从碳氮氧循环向更重元素的转化提供了实验约束。研究结合恒星模型，讨论了第一代恒星中钙的形成路径。这项工作是氟反应研究的扩展，区别于首批核心反应中的 ¹⁹F(p,α)¹⁶O。发表于 Nature 610, 656–660。","JUNA’s low-energy measurement of ¹⁹F(p,γ)²⁰Ne constrains a route from the carbon–nitrogen–oxygen cycles to heavier elements. Combined with stellar models, it suggests a pathway for calcium production in the first stars. This extends the fluorine programme beyond the initial ¹⁹F(p,α)¹⁶O reaction. Published in Nature 610, 656–660."]},
  {slug:"carbon-neutron-source-2022",reactionId:"neutron",authors:"B. Gao et al. (JUNA Collaboration)",volume:"129",pages:"132701",publishedOnline:"2022-09-23",kind:"research",language:"en",citation:"B. Gao et al. (JUNA Collaboration). Deep Underground Laboratory Measurement of ¹³C(α,n)¹⁶O in the Gamow Windows of the s and i Processes. Physical Review Letters 129, 132701 (2022). https://doi.org/10.1103/PhysRevLett.129.132701",bibtex:"@article{Gao2022NeutronSource,\n  author = {Gao, B. and others},\n  title = {Deep Underground Laboratory Measurement of {$^{13}$C($\\alpha$,n)$^{16}$O} in the Gamow Windows of the s and i Processes},\n  journal = {Physical Review Letters},\n  year = {2022},\n  volume = {129},\n  pages = {132701},\n  doi = {10.1103/PhysRevLett.129.132701},\n  url = {https://doi.org/10.1103/PhysRevLett.129.132701},\n}",doi:"10.1103/PhysRevLett.129.132701",url:"https://doi.org/10.1103/PhysRevLett.129.132701",journal:"Physical Review Letters",year:"2022",title:["深地测量恒星中子源 ¹³C(α,n)¹⁶O","Measuring the stellar neutron source ¹³C(α,n)¹⁶O"],englishTitle:"Deep Underground Laboratory Measurement of ¹³C(α,n)¹⁶O in the Gamow Windows of the s and i Processes",summary:["结合地下与地面实验，约束慢中子俘获与中间中子俘获过程的关键中子源。","Underground and surface measurements constrain a key neutron source for the s and i processes."],detail:["¹³C(α,n)¹⁶O 是恒星重元素合成的重要中子源。研究结合深地与地面测量，获得自洽的反应数据，几乎完整覆盖中间中子俘获过程（i 过程）的伽莫夫窗口，为反应率评估提供新的实验约束。发表于 Physical Review Letters 129, 132701。","The ¹³C(α,n)¹⁶O reaction supplies neutrons for stellar heavy-element production. The study combines underground and surface measurements into a self-consistent dataset, almost completely covering the i-process Gamow window and providing new experimental constraints on the reaction rate. Published in Physical Review Letters 129, 132701."]},
  {slug:"magnesium-resonance-2022",reactionId:"magnesium",authors:"Jun Su et al. (JUNA Collaboration)",volume:"67",pages:"125–132",publishedOnline:"2021-10-28",kind:"research",language:"en",citation:"Jun Su et al. (JUNA Collaboration). First result from the Jinping Underground Nuclear Astrophysics experiment JUNA: precise measurement of the 92 keV ²⁵Mg(p, γ)²⁶Al resonance. Science Bulletin 67, 125–132 (2022). https://doi.org/10.1016/j.scib.2021.10.018",bibtex:"@article{Su2022MagnesiumResonance,\n  author = {Su, Jun and others},\n  title = {First result from the Jinping Underground Nuclear Astrophysics experiment {JUNA}: precise measurement of the 92 keV {$^{25}$Mg(p, $\\gamma$)$^{26}$Al} resonance},\n  journal = {Science Bulletin},\n  year = {2022},\n  volume = {67},\n  pages = {125--132},\n  doi = {10.1016/j.scib.2021.10.018},\n  url = {https://doi.org/10.1016/j.scib.2021.10.018},\n}",doi:"10.1016/j.scib.2021.10.018",url:"https://doi.org/10.1016/j.scib.2021.10.018",journal:"Science Bulletin",year:"2022",title:["精确测量 ²⁵Mg(p,γ)²⁶Al 的 92 keV 共振","A precise measurement of the 92 keV ²⁵Mg(p,γ)²⁶Al resonance"],englishTitle:"First result from the Jinping Underground Nuclear Astrophysics experiment JUNA: precise measurement of the 92 keV ²⁵Mg(p, γ)²⁶Al resonance",summary:["为恒星中的铝-26 合成及银河系 γ 射线观测提供关键核数据。","Nuclear data for stellar aluminium-26 production and Galactic gamma-ray observations."],detail:["铝-26 基态的放射性衰变产生 1.809 MeV 特征 γ 射线，是研究银河系近期元素合成的重要线索。JUNA 首批成果精确测量了 ²⁵Mg(p,γ)²⁶Al 反应的 92 keV 共振，为恒星反应率提供关键输入。论文于 2021 年在线发表，刊于 Science Bulletin 67, 125–132（2022）。","The decay of ground-state aluminium-26 produces a characteristic 1.809 MeV gamma ray, a tracer of recent Galactic nucleosynthesis. An early JUNA result precisely measured the 92 keV resonance in ²⁵Mg(p,γ)²⁶Al, supplying a key input to stellar reaction rates. Published online in 2021 and in Science Bulletin 67, 125–132 (2022)."]},
  {slug:"fluorine-destruction-2021",reactionId:"fluorine",authors:"L. Y. Zhang et al.",volume:"127",pages:"152702",publishedOnline:"2021-10-07",kind:"research",language:"en",citation:"L. Y. Zhang et al. Direct Measurement of the Astrophysical ¹⁹F(p,αγ)¹⁶O Reaction in the Deepest Operational Underground Laboratory. Physical Review Letters 127, 152702 (2021). https://doi.org/10.1103/PhysRevLett.127.152702",bibtex:"@article{Zhang2021FluorineDestruction,\n  author = {Zhang, L. Y. and others},\n  title = {Direct Measurement of the Astrophysical {$^{19}$F(p,$\\alpha\\gamma$)$^{16}$O} Reaction in the Deepest Operational Underground Laboratory},\n  journal = {Physical Review Letters},\n  year = {2021},\n  volume = {127},\n  pages = {152702},\n  doi = {10.1103/PhysRevLett.127.152702},\n  url = {https://doi.org/10.1103/PhysRevLett.127.152702},\n}",doi:"10.1103/PhysRevLett.127.152702",url:"https://doi.org/10.1103/PhysRevLett.127.152702",journal:"Physical Review Letters",year:"2021",title:["低能区直接测量氟的质子反应","Direct measurement of low-energy proton-induced fluorine reactions"],englishTitle:"Direct Measurement of the Astrophysical ¹⁹F(p,αγ)¹⁶O Reaction in the Deepest Operational Underground Laboratory",summary:["推进渐近巨星支恒星相关能区的测量，降低氟消耗反应率的不确定度。","Measurements at energies relevant to AGB stars reduce uncertainty in fluorine-destruction rates."],detail:["¹⁹F(p,α)¹⁶O 是恒星中氟的重要消耗通道。实验利用深地低本底环境直接测量伴随 γ 射线发射的反应分支，推动相关低能区研究，并降低恒星模型中氟反应率的不确定度。发表于 Physical Review Letters 127, 152702。","The ¹⁹F(p,α)¹⁶O reaction is an important pathway for fluorine destruction in stars. Using the underground low-background environment, the experiment directly measured gamma-emitting branches at low energies and reduced reaction-rate uncertainties in stellar models. Published in Physical Review Letters 127, 152702."]},
  {slug:"juna-platform-review-2025",reactionId:"review",kind:"review",language:"en",authors:"Weiping Liu, Bing Guo, Jianjun He, Zhihong Li, Xiaodong Tang, Maria Lugaro and Gang Lian",volume:"75",pages:"271–299",publishedOnline:"2025-06-26",doi:"10.1146/annurev-nucl-121423-101021",url:"https://doi.org/10.1146/annurev-nucl-121423-101021",journal:"Annual Review of Nuclear and Particle Science",year:"2025",englishTitle:"Progress of the Jinping Underground Nuclear Astrophysics (JUNA) Experimental Platform",title:["JUNA 实验平台的发展与研究进展", "Development and progress of the JUNA experimental platform"],summary:["综述深地低本底环境、强流加速器、探测器与靶技术，以及已公开的核天体物理研究。", "A review of the underground environment, intense-beam accelerator, detectors, targets and published nuclear astrophysics research."],detail:["这篇综述梳理 JUNA 实验平台的建设、测量方法与公开成果，讨论接近或进入伽莫夫窗口的直接测量及后续研究方向。适合从装置能力和科学任务两方面了解 JUNA。在线发表于 2025 年 6 月 26 日，刊于 Annual Review of Nuclear and Particle Science 75, 271–299（2025），开放获取。", "This review describes the development of JUNA, its measurement methods and published results, including direct measurements within or near Gamow windows and future research directions. It connects the platform’s technical capabilities to its scientific programme. Published online on 26 June 2025 in Annual Review of Nuclear and Particle Science 75, 271–299 (2025), with open access."],citation:"Weiping Liu et al. Progress of the Jinping Underground Nuclear Astrophysics (JUNA) Experimental Platform. Annual Review of Nuclear and Particle Science 75, 271–299 (2025). https://doi.org/10.1146/annurev-nucl-121423-101021",bibtex:"@article{Liu2025JUNAPlatform,\n  author = {Liu, Weiping and Guo, Bing and He, Jianjun and Li, Zhihong and Tang, Xiaodong and Lugaro, Maria and Lian, Gang},\n  title = {Progress of the Jinping Underground Nuclear Astrophysics ({JUNA}) Experimental Platform},\n  journal = {Annual Review of Nuclear and Particle Science},\n  year = {2025},\n  volume = {75},\n  pages = {271--299},\n  doi = {10.1146/annurev-nucl-121423-101021},\n  url = {https://doi.org/10.1146/annurev-nucl-121423-101021}\n}"},
];

export type Reaction = {
  id: ReactionId;
  formula: string;
  tag: BilingualText;
  title: BilingualText;
  text: BilingualText;
  task: BilingualText;
  type: BilingualText;
  product: string;
  input: string;
  particle: string;
  tone: string;
  publicProgress: BilingualText;
  detector: BilingualText;
  references: string[];
};
// The initial four core reactions; published extensions remain linked to their parent programme.
export const reactions: Reaction[] = [
  { id: "carbon", formula: "¹²C(α,γ)¹⁶O", tag: ["碳与氧的起源", "The origin of carbon and oxygen"], title: ["碳氧丰度与恒星氦燃烧", "Carbon, oxygen and stellar helium burning"], text: ["氦燃烧阶段，碳核俘获一个 α 粒子，生成氧核并释放 γ 射线。这一反应与三 α 过程共同影响氦燃烧结束时碳与氧的相对丰度，影响大质量恒星的演化及其最终命运。", "During helium burning, carbon captures an alpha particle to form oxygen and emit a gamma ray. Together with the triple-alpha process, this reaction influences the carbon-to-oxygen ratio after helium burning and influences the evolution and final fate of massive stars."], task: ["在低能区直接测量极小的反应截面，为恒星模型提供实验约束。", "Directly measure tiny cross sections at low energies to constrain stellar models."], type: ["氦燃烧", "Helium burning"], product: "¹⁶O + γ", input: "¹²C + α", particle: "γ", tone: "blue", publicProgress: ["研究目标是在更低能区直接测量反应截面，结合反应模型改进恒星反应率约束。", "The programme aims to measure cross sections at lower energies and improve stellar-rate constraints together with reaction modelling."], detector: ["探测俘获反应发出的 γ 射线；结合高效率探测、屏蔽与本底抑制提取微弱信号。", "Measure capture gamma rays with efficient detectors, shielding and background rejection to identify weak signals."], references: ["juna-platform-review-2025"] },
  { id: "neutron", formula: "¹³C(α,n)¹⁶O", tag: ["重元素的中子来源", "A neutron source for heavy elements"], title: ["碳-13 为重元素合成提供中子", "Carbon-13 supplies neutrons for heavy-element synthesis"], text: ["在渐近巨星支恒星中，碳-13 与 α 粒子反应并释放中子，为慢中子俘获过程提供重要中子源。许多比铁更重的元素在这一过程中逐步形成。", "In asymptotic giant branch stars, carbon-13 reacts with alpha particles and releases neutrons. This is a major neutron source for the slow neutron-capture process that produces many elements heavier than iron."], task: ["测量低能反应截面，约束恒星中的中子产生率。", "Measure low-energy cross sections to constrain neutron production in stars."], type: ["慢中子俘获过程", "The s-process"], product: "¹⁶O + n", input: "¹³C + α", particle: "n", tone: "cyan", publicProgress: ["2022 年论文结合 CJPL 与四川大学测量，覆盖质心系能量 0.24–1.9 MeV，几乎完整覆盖 i 过程的伽莫夫窗口。", "The 2022 study combines CJPL and Sichuan University measurements at centre-of-mass energies of 0.24–1.9 MeV, covering almost the entire i-process Gamow window."], detector: ["反应产生的中子经慢化后由 ³He 正比计数管阵列记录，结合探测效率确定反应产额。", "Neutrons are moderated and counted by a ³He proportional-counter array; calibrated efficiency links the count rate to the reaction yield."], references: ["carbon-neutron-source-2022"] },
  { id: "fluorine", formula: "¹⁹F(p,α)¹⁶O", tag: ["氟的恒星演化", "The stellar evolution of fluorine"], title: ["质子反应改变恒星中的氟丰度", "Proton reactions change stellar fluorine abundances"], text: ["氟-19 俘获质子并放出 α 粒子，是恒星中氟的重要消耗通道。准确测量其低能反应率，有助于理解氟的丰度，以及渐近巨星支恒星中的氟超丰现象。", "Fluorine-19 captures a proton and emits an alpha particle, an important fluorine-destruction pathway in stars. Accurate low-energy rates help explain fluorine abundances and fluorine enhancement in asymptotic giant branch stars."], task: ["分辨低能共振及不同末态分支，检验恒星核反应网络。", "Resolve low-energy resonances and final-state branches to test stellar reaction networks."], type: ["氢燃烧", "Hydrogen burning"], product: "¹⁶O + α", input: "¹⁹F + p", particle: "α", tone: "warm", publicProgress: ["2021 年论文直接测量 ¹⁹F(p,αγ)¹⁶O 的伴随 γ 射线分支；2022 年进一步研究 ¹⁹F(p,γ)²⁰Ne 对 CNO 循环突破的影响。", "The 2021 paper measures gamma-emitting branches of ¹⁹F(p,αγ)¹⁶O. The 2022 work extends the programme to ¹⁹F(p,γ)²⁰Ne and CNO breakout."], detector: ["α 粒子发射后，若 ¹⁶O 留在激发态，其退激 γ 射线可由 BGO 阵列记录；这一方法测量伴随 γ 射线的分支。", "If alpha emission leaves ¹⁶O excited, its de-excitation gamma rays can be recorded by the BGO array. This method measures gamma-emitting branches."], references: ["fluorine-destruction-2021", "cno-breakout-2022"] },
  { id: "magnesium", formula: "²⁵Mg(p,γ)²⁶Al", tag: ["银河系的放射性示踪", "A radioactive tracer of the Galaxy"], title: ["镁铝反应连接实验与 γ 射线天文学", "Magnesium–aluminium reactions connect experiments to gamma-ray astronomy"], text: ["铝-26 基态的放射性衰变产生 1.809 MeV 特征 γ 射线，记录银河系近期的元素合成活动。镁-25 的质子俘获反应是其生成路径之一，反应率是解释天文观测的重要输入。", "Decay of ground-state aluminium-26 produces a characteristic 1.809 MeV gamma ray, tracing recent nucleosynthesis in the Galaxy. Proton capture on magnesium-25 is one production pathway, and its rate helps interpret astronomical observations."], task: ["测量低能共振及衰变分支，连接地面实验与 γ 射线天文学。", "Measure low-energy resonances and decay branches to connect laboratory experiments with gamma-ray astronomy."], type: ["镁铝循环", "The Mg–Al cycle"], product: "²⁶Al + γ", input: "²⁵Mg + p", particle: "γ", tone: "violet", publicProgress: ["首批成果精确测量 ²⁵Mg(p,γ)²⁶Al 的 92 keV 共振。论文于 2021 年在线发表，刊于 2022 年 Science Bulletin。", "An early result precisely measured the 92 keV ²⁵Mg(p,γ)²⁶Al resonance, published online in 2021 and in Science Bulletin in 2022."], detector: ["BGO 阵列记录俘获反应的 γ 射线及其级联信号，用于确定共振产额。²⁶Al 基态与同核异构态的生成分支需分别考虑。", "The BGO array records capture gamma rays and cascades to determine resonance yields. Production branches to the ²⁶Al ground state and isomer must be distinguished."], references: ["magnesium-resonance-2022"] },
];

export const credits: {label:[string,string];url:string;credit:string}[] = [
  {label:["JUNA 项目名称与实验目标","JUNA name and scientific mission"],url:"https://cjpl.tsinghua.edu.cn/column/Experiments",credit:"China Jinping Underground Laboratory / 清华大学"},
  {label:["JUNA 实验平台综述（2025）","Review of the JUNA experimental platform (2025)"],url:"https://doi.org/10.1146/annurev-nucl-121423-101021",credit:"Annual Review of Nuclear and Particle Science 75, 271–299"},
  {label:["装置与岩层覆盖综述（2024）","Facility and overburden review (2024)"],url:"https://doi.org/10.1007/s41365-024-01590-3",credit:"Nuclear Science and Techniques / JUNA collaboration"},
  {label:["面纱星云：哈勃空间望远镜观测","Veil Nebula: Hubble Space Telescope observation"],url:"https://esahubble.org/images/potw2113a/",credit:"ESA/Hubble & NASA, Z. Levay · CC BY 4.0 · WebP conversion / 图像压缩"},
  {label:["JUNA 装置实景","JUNA facility photograph"],url:"https://inrio.net/facilities",credit:"INRIO / China Institute of Atomic Energy · Original rights retained / 原权利人保留版权"},
];
