export type Paper = { doi:string; url:string; journal:string; year:string; title:[string,string]; englishTitle:string; summary:[string,string]; detail:[string,string] };
export const papers: Paper[] = [
  {doi:"10.1038/s41586-022-05230-x",url:"https://doi.org/10.1038/s41586-022-05230-x",journal:"Nature",year:"2022",title:["第一代恒星中的 CNO 循环突破反应","CNO breakout in the first stars"],englishTitle:"Measurement of ¹⁹F(p, γ)²⁰Ne reaction suggests CNO breakout in first stars",summary:["测量 ¹⁹F(p,γ)²⁰Ne 反应，为第一代恒星中钙的形成途径提供实验依据。","A measurement of ¹⁹F(p,γ)²⁰Ne constrains a pathway for calcium production in the first stars."],detail:["JUNA 对 ¹⁹F(p,γ)²⁰Ne 的低能测量，为物质从碳氮氧循环向更重元素的转化提供了实验约束。研究结合恒星模型，讨论了第一代恒星中钙的形成路径。这项工作是氟反应研究的扩展，区别于首批核心反应中的 ¹⁹F(p,α)¹⁶O。发表于 Nature 610, 656–660。","JUNA’s low-energy measurement of ¹⁹F(p,γ)²⁰Ne constrains a route from the carbon–nitrogen–oxygen cycles to heavier elements. Combined with stellar models, it suggests a pathway for calcium production in the first stars. This extends the fluorine programme beyond the initial ¹⁹F(p,α)¹⁶O reaction. Published in Nature 610, 656–660."]},
  {doi:"10.1103/PhysRevLett.129.132701",url:"https://doi.org/10.1103/PhysRevLett.129.132701",journal:"Physical Review Letters",year:"2022",title:["深地测量恒星中子源 ¹³C(α,n)¹⁶O","Measuring the stellar neutron source ¹³C(α,n)¹⁶O"],englishTitle:"Deep Underground Laboratory Measurement of ¹³C(α,n)¹⁶O in the Gamow Windows of the s and i Processes",summary:["结合地下与地面实验，约束慢中子俘获与中间中子俘获过程的关键中子源。","Underground and surface measurements constrain a key neutron source for the s and i processes."],detail:["¹³C(α,n)¹⁶O 是恒星重元素合成的重要中子源。研究结合深地与地面测量，获得自洽的反应数据，几乎完整覆盖中间中子俘获过程（i 过程）的伽莫夫窗口，为反应率评估提供新的实验约束。发表于 Physical Review Letters 129, 132701。","The ¹³C(α,n)¹⁶O reaction supplies neutrons for stellar heavy-element production. The study combines underground and surface measurements into a self-consistent dataset, almost completely covering the i-process Gamow window and providing new experimental constraints on the reaction rate. Published in Physical Review Letters 129, 132701."]},
  {doi:"10.1016/j.scib.2021.10.018",url:"https://doi.org/10.1016/j.scib.2021.10.018",journal:"Science Bulletin",year:"2022",title:["精确测量 ²⁵Mg(p,γ)²⁶Al 的 92 keV 共振","A precise measurement of the 92 keV ²⁵Mg(p,γ)²⁶Al resonance"],englishTitle:"First result from the Jinping Underground Nuclear Astrophysics experiment JUNA: precise measurement of the 92 keV ²⁵Mg(p, γ)²⁶Al resonance",summary:["为恒星中的铝-26 合成及银河系 γ 射线观测提供关键核数据。","Nuclear data for stellar aluminium-26 production and Galactic gamma-ray observations."],detail:["放射性铝-26 的衰变产生 1.809 MeV 特征 γ 射线，是研究银河系近期元素合成的重要线索。JUNA 首批成果精确测量了 ²⁵Mg(p,γ)²⁶Al 反应的 92 keV 共振，为恒星反应率提供关键输入。论文于 2021 年在线发表，刊于 Science Bulletin 67, 125–132（2022）。","The decay of radioactive aluminium-26 produces a characteristic 1.809 MeV gamma ray, a tracer of recent Galactic nucleosynthesis. An early JUNA result precisely measured the 92 keV resonance in ²⁵Mg(p,γ)²⁶Al, supplying a key input to stellar reaction rates. Published online in 2021 and in Science Bulletin 67, 125–132 (2022)."]},
  {doi:"10.1103/PhysRevLett.127.152702",url:"https://doi.org/10.1103/PhysRevLett.127.152702",journal:"Physical Review Letters",year:"2021",title:["低能区直接测量氟的质子反应","Direct measurement of low-energy proton-induced fluorine reactions"],englishTitle:"Direct Measurement of the Astrophysical ¹⁹F(p,αγ)¹⁶O Reaction in the Deepest Operational Underground Laboratory",summary:["推进渐近巨星支恒星相关能区的测量，降低氟消耗反应率的不确定度。","Measurements at energies relevant to AGB stars reduce uncertainty in fluorine-destruction rates."],detail:["¹⁹F(p,α)¹⁶O 是恒星中氟的重要消耗通道。实验利用深地低本底环境直接测量伴随 γ 射线发射的反应分支，推动相关低能区研究，并降低恒星模型中氟反应率的不确定度。发表于 Physical Review Letters 127, 152702。","The ¹⁹F(p,α)¹⁶O reaction is an important pathway for fluorine destruction in stars. Using the underground low-background environment, the experiment directly measured gamma-emitting branches at low energies and reduced reaction-rate uncertainties in stellar models. Published in Physical Review Letters 127, 152702."]},
];
export const credits: {label:[string,string];url:string;credit:string}[] = [
  {label:["JUNA 项目名称与实验目标","JUNA name and scientific mission"],url:"https://cjpl.tsinghua.edu.cn/column/Experiments",credit:"China Jinping Underground Laboratory / 清华大学"},
  {label:["JUNA 实验平台综述（2025）","Review of the JUNA experimental platform (2025)"],url:"https://doi.org/10.1146/annurev-nucl-121423-101021",credit:"Annual Review of Nuclear and Particle Science 75, 271–299"},
  {label:["装置与岩层覆盖综述（2024）","Facility and overburden review (2024)"],url:"https://doi.org/10.1007/s41365-024-01590-3",credit:"Nuclear Science and Techniques / JUNA collaboration"},
  {label:["面纱星云：哈勃空间望远镜观测","Veil Nebula: Hubble Space Telescope observation"],url:"https://esahubble.org/images/potw2113a/",credit:"ESA/Hubble & NASA, Z. Levay · CC BY 4.0 · WebP conversion / 图像压缩"},
  {label:["JUNA 装置实景","JUNA facility photograph"],url:"https://inrio.net/facilities",credit:"INRIO / China Institute of Atomic Energy · Original rights retained / 原权利人保留版权"},
];
